### ISSUE TITLE
Only include proposals that are connected to the resource that was seen just before the respective step

### ISSUE THREAD

**Issue by Humorloos** [Humorloos/semantic_web_project#10]
When showing new proposals we can rank the proposals by number of previously seen resources they are connected to. However, if a user has been browsing for a while, and went from e.g. Mannheim to Berlin, it may happen, that after some time resources are connected to many resources seen by the learner early on (related to mannheim), but not at all to berlin. So it might make sense to intruduce a condition that selects only proposals that have at least one link to the previously seen resource.

In that case we could display relations to previous resources in some other way, e.g. in a tooltip

**Comment by jsobbe** [comment]
That could help us avoid some redundancy, but I think we should still allow the user to somehow generate proposals based on all the previous resources as well, so they can see the best overall suggestions.
Might be something that we have to try and test in practice to see how well it works?

Maybe we can create some kind of factory or something similar, that allows us to easily configure a query, so we can just add/remove filters like these without having to rewrite the queries each time, when we want to change something for testing?

**Comment by Humorloos** [comment]
good idea, could be a new issue maybe?
