### ISSUE TITLE
Display the relation to the previous topic in the app

### ISSUE THREAD

**Issue by Humorloos** [Humorloos/semantic_web_project#45]
The backend logic for this is already implemented (see #11) and the property is contained in the result of `getSuggestionsForCurrentTopic` with the key `?sample_property`, we would only need to display this in the app. Furthermore for the relations, we need to display the name of the previous topic to which the relation connects the proposal (provided in binding ?previous_topic in output of getSuggestionsForCurrentTopic()).

**Comment by jsobbe** [comment]
Seems to be readable to the user, even without knowing/displaying which of the resources is the subject or object.
But needs to be checked further!
